SELECT OrderID, COUNT(OrderID)
FROM ORDERS
GROUP BY OrderID
HAVING COUNT(OrderID) > 1

DELETE FROM ORDERS
WHERE OrderID IN (
    SELECT OrderID
    FROM ORDERS
    GROUP BY OrderID
    HAVING COUNT(OrderID) > 1
)

update ORDERS set OrderID = 1419 where OrderID = 1418 and ORDERCOSTPRICE = 106;

SELECT OrderID, COUNT(OrderID)
FROM ORDERS
GROUP BY OrderID
HAVING COUNT(OrderID) > 1